CREATE TABLE IF NOT EXISTS board_types (
    id INT AUTO_INCREMENT PRIMARY KEY,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    name VARCHAR(50) NOT NULL UNIQUE,
    code VARCHAR(5) NOT NULL,
    description VARCHAR(255)
);
