// type roomsQueryType = {
//     [key: string]: string;
// };

export const amenitiesQueries = {
    addAmenities: `INSERT INTO amenities(
        air_conditioning,
        balcony,
        bathtub,
        ceiling_fan,
        clothes_dryer,
        connecting_rooms,
        cooker,
        dining_area,
        electric_kettle,
        garden_view,
        hairdryer,
        hot_water,
        ironing_set,
        kitchenete,
        microwave_oven,
        minibar,
        mountain_or_hill_view,
        non_smoking_room,
        pool_view,
        power_outlet,
        private_beach,
        safe_or_locker,
        smoking_room,
        tea_and_offee,
        telephone,
        toiletries,
        tv,
        wifi,
        room_id
        ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,

    getAllAmenities: `SELECT * FROM amenities`,

    getSingleAmenitiesById: `SELECT * FROM amenities WHERE id = ?`,

    updateSingleAmenitiesById: `UPDATE amenities SET 
    air_conditioning = ?,
    balcony = ?,
    bathtub = ?,
    ceiling_fan = ?,
    clothes_dryer = ?,
    connecting_rooms = ?,
    cooker = ?,
    dining_area = ?,
    electric_kettle = ?,
    garden_view = ?,
    hairdryer = ?,
    hot_water = ?,
    ironing_set = ?,
    kitchenete = ?,
    microwave_oven = ?,
    minibar = ?,
    mountain_or_hill_view = ?,
    non_smoking_room = ?,
    pool_view = ?,
    power_outlet = ?,
    private_beach = ?,
    safe_or_locker = ?,
    smoking_room = ?,
    tea_and_offee = ?,
    telephone = ?,
    toiletries = ?,
    tv = ?,
    wifi = ?,
    room_id = ? WHERE id = ?`,

    deleteSingleAmenitiesById: `DELETE FROM amenities WHERE id = ?`,
};
